language: python

env:
  global:
    - PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
  matrix:
    - TOXENV=py27
    - TOXENV=py26
    - TOXENV=py33
    - TOXENV=py34

sudo: true

cache:
  - $HOME/.pip-cache

install:
  - pip install tox

before_script:
  # allow ssh loopback
  - ssh-keygen -t rsa -N '' -C '' -f ~/.ssh/id_rsa
  - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
  - ssh -o StrictHostKeyChecking=no localhost true

script:
  - tox

after_failure:

after_success:

branches:
  only:
    - master
